version: "3.9"

services:
  server:
    build: .
    ports:
      - "4000:4000"
  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "docker"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
